name: tests-and-QA

on:
  push: ~

concurrency:
  group: tests-and-QA_${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - run: npm install-ci-test
